### ISSUE TITLE
Blood Curse of the eyeless bug (Blood hunter feature)

### ISSUE THREAD

**Issue by Kodokbotak** [kakaroto/Beyond20#1084]
There is a bug when trying to send Blood Curse of the Eyeless feature of Blood Hunter from dndbeyond to roll20. It doesn't show the whole description, instead just rolls a die and it's not a correct die mind you. Please fix it!

**Comment by kakaroto** [comment]
Thanks for the report. There was a typo (`Bloodhunter` instead of `Blood Hunter`) which is now fixed.

**Comment by Kodokbotak** [comment]
I doesn't seem to be fixed on firefox. 

- It still won't display the whole description on roll20, instead it just rolls a die. 

- it still rolls the wrong die (at 6th lvl it rolls a d4 instead of a d6).

Does the fix not work on firefox?

**Comment by Aeristoka** [comment]
> I doesn't seem to be fixed on firefox.
> 
> * It still won't display the whole description on roll20, instead it just rolls a die.
> * it still rolls the wrong die (at 6th lvl it rolls a d4 instead of a d6).
> 
> Does the fix not work on firefox?

You'll have to do this: https://github.com/kakaroto/Beyond20#developer-mode-installation

A new release has NOT been created yet to have this on the official release.
