### ISSUE TITLE
Class Features seem to be broken

### ISSUE THREAD

**Issue by dmportella** [kakaroto/Beyond20#1164]
**Describe the bug**
Class Features seem to be broken, they changed classes for them so the selector is not working (style component class names again).

![image](https://github.com/user-attachments/assets/d86a5aeb-b65d-40f3-bebc-cf68aa83b601)

genie warlock (dao) but character option is missing.

**Expected behavior**
Should see Genie Wrath being applied.

**Screenshots**
Broken Code now (selector line)

![image](https://github.com/user-attachments/assets/1cc13e59-7177-416b-807a-ffcc7cc3eada)

HTML now is styled componenterised >:(

![image](https://github.com/user-attachments/assets/b2febfa6-0c25-4a6d-9460-c3e08ada49b7)

**Browser Info (please complete the following information):**
 - Browser chrome
 - Version 128.0.6613.138 

**Additional context**
Adding fix for it shortly

**Comment by DMMeleedy** [comment]
Is this why my barbarian character no longer has a Rage button to slide on in the beyond20 interface?

**Comment by kakaroto** [comment]
> Is this why my barbarian character no longer has a Rage button to slide on in the beyond20 interface?

yes indeed!

**Comment by DMMeleedy** [comment]
Do you know when your fix will make it to the official chrome extension?

**Comment by dmportella** [comment]
> Do you know when your fix will make it to the official chrome extension?

not sure, change has been accepted and merge so soon as it is published

**Comment by Kodokbotak** [comment]
yeah also blood hunter's crimson rite toggle has disappeared

**Comment by dmportella** [comment]
> yeah also blood hunter's crimson rite toggle has disappeared

that should be fixed with the PR that was merged yesterday, i will test it

**Comment by dmportella** [comment]
> yeah also blood hunter's crimson rite toggle has disappeared

with the fix the toggle comes back <3

Wait for a couple days for it to be pulished

![image](https://github.com/user-attachments/assets/01c4f038-d827-4eea-80d8-de23828cd44f)

**Comment by Kodokbotak** [comment]
nooice!

**Comment by DMMeleedy** [comment]
This is not showing up for me in beyond20 either. Is this a feature that will be fixed by this bug fix, or was it not supported to begin with?

Savage Attackerfree-rules, pg. 201
From
Soldier
Once per turn when you hit a target with a weapon, you can roll the weapon’s damage dice twice and use either roll against the target.

**Comment by dmportella** [comment]
> This is not showing up for me in beyond20 either. Is this a feature that will be fixed by this bug fix, or was it not supported to begin with?
> 
> Savage Attackerfree-rules, pg. 201 From Soldier Once per turn when you hit a target with a weapon, you can roll the weapon’s damage dice twice and use either roll against the target.

that should be fixed after this patch is applied

**Comment by shazam2323** [comment]
Has this been pushed yet? My ifreeti (fire genie) still doesn't have genie's wrath showing

**Comment by dmportella** [comment]
> Has this been pushed yet? My ifreeti (fire genie) still doesn't have genie's wrath showing

change has been merged just awaiting to be published <3

**Comment by SquishyMochi514** [comment]
For the record, this also occur for Bloodhunter special feature like crimson rite

**Comment by Wulfson** [comment]
Also missing Paladin: Improved Divine Smite automatically adding the extra damage, and the Feat: Great Weapon Master toggle to do the -5/+10; ran into that last night

**Comment by kakaroto** [comment]
For everyone who comments here about something missing, note that as far as we know, every character specific class feature is missing and broken.
Please note that this has been fixed already, but that doesn't mean it's released and it doesn't mean your extension on your local PC has been updated either.
I'll be releasing the update with the fix later this weekend, then it can take a week or more before the new release is reviewed by the chrome/firefox/edge store teams and it becomes publicly available.
Then you'll need your browser to see the update and install it (you could force it by going to the chrome store and manually updating it, once that release becomes publicly available).

Either be patient, or read here on how to install the development version: https://github.com/kakaroto/Beyond20#developer-mode-installation
Thank you.

**Comment by kakaroto** [comment]
I've just released 2.9.6, see the release notes here: https://patreon.com/posts/beyond20-v2-9-6-112584731
It's pending review at the moment on the chrome/edge/firefox stores.
I'll close this ticket once the browser stores approve the update.

**Comment by kakaroto** [comment]
The 2.9.6 release was finally approved on the firefox store today, making it now officially released in all 3 stores.
Closing this issue.

**Comment by shazam2323** [comment]
I'm now on 2.9.6 but genie's wrath is still missing

**Comment by kakaroto** [comment]
> I'm now on 2.9.6 but genie's wrath is still missing

D&D Beyond updated their website yesterday which broke things again, we'll be releasing an update ASAP to fix it.
