### ISSUE TITLE
DnDBeyond Custom Action, Description & Pics wont post to VTT... Thanks for addressing :))

### ISSUE THREAD

**Issue by tjagz123** [kakaroto/Beyond20#1219]
**Describe the bug**
**DnDBeyond Custom Action wont post to VTT**

**To Reproduce**
1. Go to - **open DnD Beyond Character Sheet**
2. Click on - **Actions, Manage Custom, Click any custom action,** 

**Expected behavior**
**When you you click on Beyond 20 button the description would display on VTT, and also Display to VTT button is missing** 

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.

![image](https://github.com/user-attachments/assets/2f92ca91-1ba1-4a62-a35a-943521f3edd7)

###This how is used to look before today's patch...

![image](https://github.com/user-attachments/assets/58e5fb2c-fbbd-4acd-8974-847f6c626793)

**Browser Info (please complete the following information):**
 - Browser **[chrome and firefox]**
 - Version [**1 / 9 / 25 Version]**
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.

**Comment by kakaroto** [comment]
Which version were you on? I released 2.11.1 yesterday which addressed this, so I think you just didn't yet have your browser updating the extension for you but if you update it, it should work.
Please confirm, thanks!

**Comment by tjagz123** [comment]
Hi there, by the way love Beyond20 app... I'm a Ko-Fi supporter :))
Yes I'm using  2.11.1 in both Firefox & Chrome. Both of these browsers are up to date. 
I checked the Beyond20 Quick setting on the DnD Beyond Character page too... nothing odd there. 
I'm sure it's something simple... Any Thoughts? Thanks in advance!!

**Comment by tjagz123** [comment]
Just rebooted PC, no change. 🤔

**Comment by dmportella** [comment]
@kakaroto yeah not I got the main attacked working, but had not seen the descriptions not showing, i found the issue - styledcomponent change on the description, I will make a patch for it now.

**Comment by tjagz123** [comment]
Hi @kakaroto @dmportella ... Thanks for the followup and communication... :)) I just checked DnD Beyond and the issue still persists. I rebooted my PC and tried Firefox & Chrome. Does the patch take a few days to publish?

**Comment by dmportella** [comment]
> Hi @kakaroto @dmportella ... Thanks for the followup and communication... :)) I just checked DnD Beyond and the issue still persists. I rebooted my PC and tried Firefox & Chrome. Does the patch take a few days to publish?

HI Sorry it has not yet been released so you wont see the fixed in production yet. But fear not it will be release soon.

**Comment by tjagz123** [comment]
Thanks.... great communication! ❣️
Looking forward to the update :)

**Comment by tjagz123** [comment]
Hello, the issue persists... :(
The descriptions aren't showing up in the VTT. 
I have tried Firefox & Chrome. Thanks for addressing

**Comment by kakaroto** [comment]
> Hello, the issue persists... :( The descriptions aren't showing up in the VTT. I have tried Firefox, Edge & Chrome. Thanks for addressing

Did you check the version of the extension you were using? Did you make sure it was updated? The Firefox version didn't update until this morning (they're really slow to approve updates).
I've tested it without issues on my side:

Character sheet:
![Image](https://github.com/user-attachments/assets/5810f6a9-fd6b-4707-8938-93416b866785)

In roll20:

![Image](https://github.com/user-attachments/assets/8a9ccb7d-db80-42b3-b765-7d2f634037c7)

If you have a link to your character sheet that can help us test something more specific, then that could help reproduce your issue and fix it, but as it stands, it does seem to have been fixed.

**Comment by tjagz123** [comment]
Hi Youness, Kakaroto,

Yes it works, for some reason the Beyond 20 extension was not set to auto update. Tried on multiple PCs works great.

Thanks for the great work and application. 💯

![Image](https://github.com/user-attachments/assets/1902875b-2536-4cd4-8377-e25462ed6bd5)

![Image](https://github.com/user-attachments/assets/d7b737de-75e5-434e-b79e-62adf84fdb7b)
